[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32 --baud 2000000"
linker = "/home/kikuo/.rustup/toolchains/esp/xtensa-esp-elf/esp-14.2.0_20240906/xtensa-esp-elf/bin/xtensa-esp32-elf-gcc"

[env]

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-Z", "stack-protector=all",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core"]
